$solutionPath = split-path $MyInvocation.MyCommand.Definition
$getDotNet = join-path $solutionPath "tools\install.ps1"

$env:DOTNET_INSTALL_DIR="$(Convert-Path "$PSScriptRoot")\.dotnet\win7-x64"
if (!(Test-Path $env:DOTNET_INSTALL_DIR))
{
    mkdir $env:DOTNET_INSTALL_DIR | Out-Null
}
    
& $getDotNet

$env:DOTNET_HOME = "$env:DOTNET_INSTALL_DIR\cli"
$env:PATH = "$env:DOTNET_HOME\bin;$env:PATH"

$autoGeneratedVersion = $false

# Update build number during CI
if ($env:BuildSemanticVersion -eq $null) {
    $autoVersion = [math]::floor((New-TimeSpan $(Get-Date) $(Get-Date -month 1 -day 1 -year 2016 -hour 0 -minute 0 -second 0)).TotalMinutes * -1).ToString() + "-" + (Get-Date).ToString("ss")
    $env:BuildSemanticVersion = "dev-" + $autoVersion
    $autoGeneratedVersion = $true
    
    Write-Host "Set version to $autoVersion"
}

$projectJson = "src\dotnet-test-xunit\project.json"
$content = get-content $projectJson
$content = $content.Replace("99.99.99-dev", "1.0.0-$env:BuildSemanticVersion")
set-content $projectJson $content -encoding UTF8

dir "test" | where {$_.PsIsContainer} |
foreach {
    $projectJson = "test\$_\project.json"
    $content = get-content $projectJson
    $content = $content.Replace("99.99.99-dev", "1.0.0-$env:BuildSemanticVersion")
    set-content $projectJson $content -encoding UTF8
}

# Restore packages and build product
& dotnet restore "src\dotnet-test-xunit"
& dotnet pack "src\dotnet-test-xunit" --configuration Release --output "artifacts\packages"

#restore, compile, and run tests
& dotnet restore "test" -s "artifacts\packages"

# workaround for dotnet-restore from the root failing for these tests since their dependencies aren't built yet
dir "test" | where {$_.PsIsContainer} |
foreach {
    pushd "test\$_"
    & dotnet build
    & dotnet test
    popd
}


$projectJson = "src\dotnet-test-xunit\project.json"
$content = get-content $projectJson
$content = $content.Replace("1.0.0-$env:BuildSemanticVersion", "99.99.99-dev")
set-content $projectJson $content -encoding UTF8

dir "test" | where {$_.PsIsContainer} |
foreach {
    $projectJson = "test\$_\project.json"
    $content = get-content $projectJson
    $content = $content.Replace("1.0.0-$env:BuildSemanticVersion", "99.99.99-dev")
    set-content $projectJson $content -encoding UTF8
}

if ($autoGeneratedVersion){
    $env:BuildSemanticVersion = $null
}